# https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions
name: 'PR Auto Label'
description: 'PR auto set label follow its title.'
author: 'xrkffgg'

# https://actions-cool.github.io/github-action-branding/
branding:
  icon: 'skip-back'
  color: 'purple'

inputs:
  token:
    description: Secret GitHub API token to use for making API requests.
    default: ${{ github.token }}
    required: true
  enum:
    description: list that need to deal
  format:
    description: label format
  extra:
    description: extra deal

#outputs:
#  result:
#    description: action result

runs:
  using: 'node12'
  main: 'dist/index.js'
